use_frameworks!

platform :ios, '13.0'

target 'QCAttributedStringBuilder_Example' do
  pod 'QCAttributedStringBuilder', :path => '../'

  target 'QCAttributedStringBuilder_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
